In [1]:
!pip install numpy

In [2]:
import numpy as np

In [6]:
### create array using numpy
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
arr1.shape

[1 2 3 4 5]
<class 'numpy.ndarray'>


(5,)

In [9]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [10]:
## 2D Array
arr2=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
print("Number of Direction :",arr.ndim)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
Number of Direction : 2
int64
8


In [20]:
### Numpy Vectorized Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])

### Element wise addition
print("Addition :", arr1+arr2)

## Element wise substraction
print("Substraction :",arr1-arr2)

print("Multiplication", arr1*arr2)
print("Division:",arr1/arr2)



Addition : [ 5  7  9 11 13]
Substraction : [-3 -3 -3 -3 -3]
Multiplication [ 4 10 18 28 40]
Division: [0.25       0.4        0.5        0.57142857 0.625     ]


In [23]:
### Univeral function
arr=np.array([1,2,3,4,5,6])
## square root

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
### array slicing and indexing

arr=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])

print("Array \n",arr)

Array 
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [27]:
arr[0][0]

np.int64(1)

In [30]:
print(arr[1:,2:])

[[ 6 11]
 [ 9 12]]


In [33]:
arr[0:2,2:]

array([[ 3, 10],
       [ 6, 11]])

In [35]:
##  Modify array element

arr[0,0]=100
print(arr)

[[100   2   3  10]
 [  4   5   6  11]
 [  7   8   9  12]]


In [36]:
### Statistical concepts---Normalization
## to have a mean of 0 and standard devaition of 1

data=np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev=np.std(data)

## Normalize the data

normalized_data=(data-mean)/std_dev
print("Normalized data :", normalized_data)


Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [39]:
data=np.array([1,2,3,4,5])
 
## mean
mean=np.mean(data)
print("Mean :", mean)

## Meadian
median=np.median(data)
print("Median :", median)

## Standard deviation
std_dev=np.std(data)
print("Standard Devation :", std_dev)

## Variance
variance=np.var(data)
print("vaiance :", variance)

Mean : 3.0
Median : 3.0
Standard Devation : 1.4142135623730951
vaiance : 2.0


In [41]:
## Logical Operation

data=np.array([1,2,3,4,5,6,7,8,9,10])
data[data>5]

array([ 6,  7,  8,  9, 10])